import { Section } from '../parser.js';

const MAX_SECTION_CHARS = 500;
const MAX_TOTAL_CHARS = 3800;
const REQUIRED_TYPES = ['identity', 'rules', 'focus', 'routing'];

function stripFilePaths(text: string): string {
  return text
    // Home-relative paths: ~/...
    .replace(/~\/[\w.\-/]+/g, '[path removed]')
    // Bash home env: $HOME/... or ${HOME}/...
    .replace(/\$(?:HOME|\{HOME\})\/[\w.\-/]+/g, '[path removed]')
    // Absolute Unix user paths: /Users/..., /home/... (spaces allowed for macOS)
    .replace(/\/(?:Users|home)\/[\w.\-/ ]+/g, '[path removed]')
    // Absolute Unix system/app paths: /opt, /var, /srv, /mnt, /tmp, /etc, /usr, /root, /private, /Volumes, /data, /workspace
    // (no spaces allowed — these shouldn't contain spaces and we don't want to over-strip sentences)
    .replace(/\/(?:opt|var|srv|mnt|tmp|etc|usr|root|private|Volumes|data|workspace)\/[\w.\-/]+/g, '[path removed]')
    // file:// URIs
    .replace(/file:\/\/\/?[\w.\-/]+/g, '[path removed]')
    // Windows absolute paths: C:\Users\...
    .replace(/[A-Za-z]:\\[\w.\-\\ ]+/g, '[path removed]')
    // Windows env vars: %USERPROFILE%\..., %APPDATA%\..., etc.
    .replace(/%(?:USERPROFILE|APPDATA|LOCALAPPDATA|HOMEPATH|HOMEDRIVE)%\\[\w.\-\\ ]+/g, '[path removed]');
}

function truncateSection(body: string, maxChars: number): string {
  if (body.length <= maxChars) return body;
  return body.slice(0, maxChars).trimEnd() + '\n\n[...truncated for Claude.ai character limits]';
}

export function generateEcoB(sections: Section[], summary: string | null): string {
  const now = new Date();
  const timestamp = now.toISOString().replace('T', ' ').slice(0, 16);

  let parts: string[] = [];
  parts.push(`[Generated by Claudeverse — last synced ${timestamp}]`);
  parts.push('');

  const title = sections.find(s => s.level === 1);
  if (title) {
    parts.push(`# ${title.heading}`);
    parts.push('');
  }

  for (const type of REQUIRED_TYPES) {
    const section = sections.find(s => s.type === type);
    if (section) {
      const cleanBody = stripFilePaths(section.body);
      parts.push(`## ${section.heading}`);
      parts.push('');
      parts.push(cleanBody);
      parts.push('');
    }
  }

  const conventions = sections.find(s => s.type === 'conventions');
  if (conventions) {
    const cleanBody = stripFilePaths(conventions.body);
    const truncated = truncateSection(cleanBody, MAX_SECTION_CHARS);
    parts.push(`## ${conventions.heading}`);
    parts.push('');
    parts.push(truncated);
    parts.push('');
  }

  const customSections = sections.filter(s => s.type === 'custom');
  for (const section of customSections) {
    if (section.body.length <= MAX_SECTION_CHARS) {
      const cleanBody = stripFilePaths(section.body);
      parts.push(`## ${section.heading}`);
      parts.push('');
      parts.push(cleanBody);
      parts.push('');
    }
  }

  if (summary) {
    parts.push('## Recent Context');
    parts.push('');
    parts.push(summary);
    parts.push('');
  }

  let result = parts.join('\n');
  if (result.length > MAX_TOTAL_CHARS) {
    result = result.slice(0, MAX_TOTAL_CHARS) + '\n\n[...truncated — run claudeverse sync to regenerate]';
  }

  return result;
}
