import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, rmSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { runSync } from '../../src/commands/sync.js';

const TEST_DIR = join(process.cwd(), '.test-claudeverse-sync');

function setupTestDir() {
  mkdirSync(join(TEST_DIR, 'daily'), { recursive: true });
  mkdirSync(join(TEST_DIR, 'generated', 'eco-a'), { recursive: true });

  writeFileSync(join(TEST_DIR, 'CLAUDE.md'), `# Test \u2014 Claude Instructions

## Identity
I am a tester.

## Rules
- Be thorough

## Current Focus
Testing Claudeverse.

## Tool Routing

| Task | Suggest | Why |
|------|---------|-----|
| Code | CLI | FS |
`);

  writeFileSync(join(TEST_DIR, '.claudeverse.yaml'), `
anthropic_api_key_env: ANTHROPIC_API_KEY
summary:
  model: claude-sonnet-4-6
  days_to_summarize: 7
  max_summary_words: 500
targets:
  eco_a:
    enabled: true
    claude_md_path: ${join(TEST_DIR, 'generated', 'eco-a', 'CLAUDE.md')}
    memory_path: ${join(TEST_DIR, 'generated', 'eco-a', 'memory')}
  eco_b:
    enabled: true
    copy_to_clipboard: false
  eco_c:
    enabled: false
daily:
  retention_days: 30
`);
}

describe('sync command', () => {
  beforeEach(() => {
    if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true });
    setupTestDir();
  });
  afterEach(() => {
    if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true });
  });

  it('generates Eco A output without daily logs', async () => {
    await runSync({ baseDir: TEST_DIR, skipApi: true, quiet: true });
    const ecoAPath = join(TEST_DIR, 'generated', 'eco-a', 'CLAUDE.md');
    expect(existsSync(ecoAPath)).toBe(true);
    const content = readFileSync(ecoAPath, 'utf-8');
    expect(content).toContain('I am a tester');
    expect(content).toContain('Tool Routing');
    expect(content).not.toContain('Recent Context');
  });

  it('generates Eco B output', async () => {
    await runSync({ baseDir: TEST_DIR, skipApi: true, quiet: true });
    const ecoBPath = join(TEST_DIR, 'generated', 'eco-b.md');
    expect(existsSync(ecoBPath)).toBe(true);
    const content = readFileSync(ecoBPath, 'utf-8');
    expect(content).toContain('Generated by Claudeverse');
    expect(content).toContain('I am a tester');
  });

  it('reads daily logs when present', async () => {
    writeFileSync(
      join(TEST_DIR, 'daily', '2026-04-03.md'),
      '# Daily Log \u2014 2026-04-03\n\n- **10:00** \u2014 Wrote tests',
    );
    await runSync({ baseDir: TEST_DIR, skipApi: true, quiet: true });
    const ecoAPath = join(TEST_DIR, 'generated', 'eco-a', 'CLAUDE.md');
    const content = readFileSync(ecoAPath, 'utf-8');
    expect(content).not.toContain('Recent Context');
  });
});
