import { describe, it, expect } from 'vitest';
import { generateEcoB } from '../../src/generators/eco-b.js';
import { parseSections } from '../../src/parser.js';

const SOURCE = `# Test User — Claude Instructions

## Identity
Director of IT at Acme Corp.

## Rules
- Never delete production data
- Always ask before infra changes

## Conventions
${'x'.repeat(2000)}

## Current Focus
Migrating to Azure.

## Tool Routing

| Task | Suggest | Why |
|------|---------|-----|
| Code | CLI | Filesystem |

## My Custom Notes
${'y'.repeat(1000)}
`;

describe('generateEcoB', () => {
  it('always includes Identity, Rules, Focus, Routing', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoB(sections, null);
    expect(result).toContain('Director of IT');
    expect(result).toContain('Never delete production data');
    expect(result).toContain('Migrating to Azure');
    expect(result).toContain('Tool Routing');
  });

  it('includes Claudeverse header', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoB(sections, null);
    expect(result).toContain('Generated by Claudeverse');
  });

  it('abbreviates long Conventions section', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoB(sections, null);
    expect(result.length).toBeLessThan(SOURCE.length);
  });

  it('strips file paths from output', () => {
    const sections = parseSections(`# Test

## Rules
Always check ~/.claude/CLAUDE.md and ~/Code/project before editing.
`);
    const result = generateEcoB(sections, null);
    expect(result).not.toContain('~/.claude/CLAUDE.md');
    expect(result).not.toContain('~/Code/project');
  });

  it('strips broadened path patterns — unix system/app dirs, brace env, file:// URIs, windows env vars', () => {
    const sections = parseSections(`# Test

## Rules
- Config at /opt/projects/secret-client/env
- Logs in /var/log/myapp.log
- Backup on /mnt/nas/backups
- Scratch in /tmp/work
- System: /etc/nginx/sites-enabled/default
- App dir: /usr/local/share/myapp
- Mount at /Volumes/SecretDrive/keys
- Brace var: \${HOME}/credentials
- URI: file:///Users/test/private/key.pem
- Windows: %USERPROFILE%\\Documents\\secrets
- Windows: %APPDATA%\\MyApp\\config.json
`);
    const result = generateEcoB(sections, null);
    expect(result).not.toContain('/opt/projects/secret-client');
    expect(result).not.toContain('/var/log/myapp');
    expect(result).not.toContain('/mnt/nas/backups');
    expect(result).not.toContain('/tmp/work');
    expect(result).not.toContain('/etc/nginx');
    expect(result).not.toContain('/usr/local/share/myapp');
    expect(result).not.toContain('/Volumes/SecretDrive');
    expect(result).not.toContain('${HOME}/credentials');
    expect(result).not.toContain('file:///Users/test/private');
    expect(result).not.toContain('%USERPROFILE%\\Documents');
    expect(result).not.toContain('%APPDATA%\\MyApp');
  });

  it('preserves non-path content that looks path-like (TCP/IP, version strings, Input/Output)', () => {
    const sections = parseSections(`# Test

## Rules
- Use TCP/IP networking
- Version 1.2/3.4 compatibility required
- Handle Input/Output asynchronously
- Read the README first before editing
`);
    const result = generateEcoB(sections, null);
    expect(result).toContain('TCP/IP');
    expect(result).toContain('1.2/3.4');
    expect(result).toContain('Input/Output');
    expect(result).toContain('README');
  });

  it('appends summary when provided', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoB(sections, 'You shipped the CRM.');
    expect(result).toContain('Recent Context');
    expect(result).toContain('shipped the CRM');
  });
});
