import { describe, it, expect } from 'vitest';
import { generateEcoA } from '../../src/generators/eco-a.js';
import { parseSections } from '../../src/parser.js';

const SOURCE = `# Test User — Claude Instructions

## Identity
I am a test user.

## Rules
- Rule one
- Rule two

## Conventions
Use TypeScript.

## Current Focus
Building Claudeverse.

## Tool Routing

| Task | Suggest | Why |
|------|---------|-----|
| Code | CLI | Filesystem |
`;

describe('generateEcoA', () => {
  it('includes all sections from source', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoA(sections, null);
    expect(result).toContain('Test User');
    expect(result).toContain('Rule one');
    expect(result).toContain('Use TypeScript');
    expect(result).toContain('Building Claudeverse');
    expect(result).toContain('Tool Routing');
  });

  it('appends recent context when provided', () => {
    const sections = parseSections(SOURCE);
    const summary = 'You deployed the CRM to Azure last week.';
    const result = generateEcoA(sections, summary);
    expect(result).toContain('## Recent Context');
    expect(result).toContain('deployed the CRM');
    expect(result).toContain('auto-generated by Claudeverse');
  });

  it('omits recent context section when summary is null', () => {
    const sections = parseSections(SOURCE);
    const result = generateEcoA(sections, null);
    expect(result).not.toContain('Recent Context');
  });
});
